###
POST https://credentials-lambda.herokuapp.com/api/auth/Register
Content-Type: application/json

{
    "username": "Amin",
    "password": "Amin"
}

###
POST https://credentials-lambda.herokuapp.com/api/auth/Login
Content-Type: application/json

{
    "username": "Hamid",
    "password": "Hamid"
}

###
GET https://credentials-lambda.herokuapp.com/api/jokes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJ1c2VybmFtZSI6IkhhbWlkIiwiaWF0IjoxNTkyMTY1ODQwLCJleHAiOjE1OTIxNjU5NjB9.1zKf1fm16AZHUTYALHjqpFPNY2vpcsaXdgQ6YBzOy6c

###
GET https://credentials-lambda.herokuapp.com/api/Users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJ1c2VybmFtZSI6IkhhbWlkIiwiaWF0IjoxNTkyMTY1ODQwLCJleHAiOjE1OTIxNjU5NjB9.1zKf1fm16AZHUTYALHjqpFPNY2vpcsaXdgQ6YBzOy6c

