###
POST http://localhost:3300/api/auth/Register
Content-Type: application/json

{
    "username": "Hamid",
    "password": "Hamid"
}

###
POST http://localhost:3300/api/auth/Login
Content-Type: application/json

{
    "username": "Hamid",
    "password": "Hamid"
}

###
GET http://localhost:3300/api/jokes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJ1c2VybmFtZSI6IkhhbWlkIiwiaWF0IjoxNTkyMTU4MjQ3LCJleHAiOjE1OTIxNTgzNjd9.JTCo62i6MKTG25EhIF08-cxNDwu5suNzZxUDfByflU8

###
GET http://localhost:3300/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWJqZWN0IjoxLCJ1c2VybmFtZSI6IkhhbWlkIiwiaWF0IjoxNTkyMTU4MjQ3LCJleHAiOjE1OTIxNTgzNjd9.JTCo62i6MKTG25EhIF08-cxNDwu5suNzZxUDfByflU8

